title: "Adiwena Putra"
subtitle: "Verilog & Very Lost"   # optional line under the title
name: "Adiwena Putra"
description: "KAIST EE PhD — computer architecture, chip design, and privacy-preserving accelerators (FHE/ZKP)."

url: "https://adiwenaputra.github.io"   # keep this for now (change later if you buy a domain)
baseurl: ""                              # keep empty for a user/organization site

locale: "en-US"
email: "adiwena.research@gmail.com"
timezone: "Asia/Seoul"

# Color skin (try a built-in first; we’ll customize in step 7)
minimal_mistakes_skin: "mint"   # try: "mint", "neon", "plum", etc.

# Search (we add a Search page in step 5)
search: true

author:
  name: "Adiwena Putra"
  avatar: "/assets/images/logo.png"            # add this image in step 6
  bio: "PhD candidate at KAIST EE, researching computer architecture and chip design."
  location: "Daejeon, South Korea"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:YOUR_EMAIL@..."
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/AdiwenaPutra"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "YOUR_SCHOLAR_URL"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "YOUR_LINKEDIN_URL"

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# (Optional) Google Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-XXXXXXX"
    anonymize_ip: true
